"""03 modify row name from table actions.

Revision ID: 0091ea2e56fb
Revises: 7752b19a3e50
Create Date: 2022-10-30 08:39:52.986338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0091ea2e56fb"
down_revision = "7752b19a3e50"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.add_column("actions", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("actions", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.add_column(
        "actions",
        sa.Column(
            "value", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("actions", "is_active")
    # ### end Alembic commands ###
