"""02 ADD DESCRIPTION COLUMN.

Revision ID: 7752b19a3e50
Revises: a7c732a8f6e7
Create Date: 2022-09-12 12:51:56.553658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7752b19a3e50"
down_revision = "a7c732a8f6e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.add_column(
        "actions", sa.Column("description", sa.String(length=250), nullable=True)
    )
    op.add_column(
        "modules", sa.Column("description", sa.String(length=250), nullable=True)
    )
    op.add_column(
        "role_actions", sa.Column("description", sa.String(length=250), nullable=True)
    )
    op.add_column(
        "roles", sa.Column("description", sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.drop_column("roles", "description")
    op.drop_column("role_actions", "description")
    op.drop_column("modules", "description")
    op.drop_column("actions", "description")
    # ### end Alembic commands ###
